[build-system]
requires = ["setuptools >= 78", "setuptools-scm >= 8.2"]
build-backend = "setuptools.build_meta"


[project]
name = "mopidy-musicbox-webclient"
description = "Mopidy MusicBox web extension"
readme = "README.rst"
requires-python = ">= 3.13"
license = { text = "Apache-2.0" }
authors = [
    { name = "Wouter van Wijk", email = "woutervanwijk@gmail.com" },
]
classifiers = [
    "Environment :: No Input/Output (Daemon)",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Sound/Audio :: Players",
]
dynamic = ["version"]
dependencies = [
    "mopidy >= 4.0.3",
    "pykka >= 4.1",
]

[project.urls]
Homepage = "https://github.com/pimusicbox/mopidy-musicbox-webclient"
Repository = "https://github.com/pimusicbox/mopidy-musicbox-webclient"
Changelog = "https://github.com/pimusicbox/mopidy-musicbox-webclient/blob/develop/CHANGELOG.rst"

[project.entry-points."mopidy.ext"]
musicbox_webclient = "mopidy_musicbox_webclient:Extension"


[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "release" },
    { include-group = "test" },
]
lint = ["ruff"]
release = ["build", "twine"]
test = ["pytest", "pytest-cov"]


[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["mopidy_musicbox_webclient*"]

[tool.setuptools.package-data]
"*" = ["*.conf"]
"mopidy_musicbox_webclient" = ["static/**"]


[tool.setuptools_scm]
# This section, even if empty, must be present for setuptools_scm to work


[tool.ruff]
target-version = "py313"
line-length = 80
extend-exclude = ["src/mopidy_musicbox_webclient/static"]

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "W",  # pycodestyle warnings
]

[tool.ruff.lint.isort]
known-first-party = ["mopidy_musicbox_webclient"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "tests",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
tests = ["tests"]


[tool.coverage.paths]
source = ["src/", "*/site-packages/"]

[tool.coverage.run]
source_pkgs = ["mopidy_musicbox_webclient"]

[tool.coverage.report]
show_missing = true


[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    # Fail tests on warnings from our own code
    "error:::mopidy_musicbox_webclient",
]
