[tox]
requires = tox >= 4.22
envlist = py313, ruff-check, ruff-format

[testenv]
sitepackages = true
dependency_groups = test
commands =
    python -m pytest \
        --basetemp={envtmpdir} \
        --cov=mopidy_musicbox_webclient --cov-report=term-missing \
        {posargs}

[testenv:ruff-check]
skip_install = true
dependency_groups = lint
commands = ruff check {posargs:.}

[testenv:ruff-format]
skip_install = true
dependency_groups = lint
commands = ruff format --check --diff {posargs:.}
